  addCommentToPost[m
  authenticationUsingSessions[m
  commentModel[m
  deletePosts[m
* [32mdisplayDateOnPost[m
  handlebars/main[m
  login2logout[m
  main[m
  modelsCreation[m
  postPost[m
  sessions[m
  showPostsInDashboard[m
  signUpUser[m
  [31mremotes/heroku/main[m
  [31mremotes/origin/addCommentToPost[m
  [31mremotes/origin/authenticationUsingSessions[m
  [31mremotes/origin/commentModel[m
  [31mremotes/origin/deletePosts[m
  [31mremotes/origin/displayDateOnPost[m
  [31mremotes/origin/handlebars/main[m
  [31mremotes/origin/login2logout[m
  [31mremotes/origin/main[m
  [31mremotes/origin/modelsCreation[m
  [31mremotes/origin/postPost[m
  [31mremotes/origin/sessions[m
  [31mremotes/origin/showPostsInDashboard[m
  [31mremotes/origin/signUpUser[m
